/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kohsuke_kprofiler_API */

#ifndef _Included_org_kohsuke_kprofiler_API
#define _Included_org_kohsuke_kprofiler_API
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kohsuke_kprofiler_API
 * Method:    enableAll
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_kohsuke_kprofiler_API_enableAll
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_kohsuke_kprofiler_API
 * Method:    enableThread
 * Signature: (Ljava/lang/Thread;Z)V
 */
JNIEXPORT void JNICALL Java_org_kohsuke_kprofiler_API_enableThread
  (JNIEnv *, jclass, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
